### ISSUE TITLE
Exception at the first run

### ISSUE THREAD

**Issue by guberm** [VedankPurohit/LiveRecall#11]
2024-06-14 15:58:36.496 Uncaught exception
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\tornado\http1connection.py", line 278, in _read_message
    delegate.finish()
  File "C:\Python\Python310\lib\site-packages\tornado\routing.py", line 268, in finish
    self.delegate.finish()
  File "C:\Python\Python310\lib\site-packages\tornado\web.py", line 2399, in finish
    self.execute()
  File "C:\Python\Python310\lib\site-packages\tornado\web.py", line 2421, in execute
    self.handler = self.handler_class(
  File "C:\Python\Python310\lib\site-packages\tornado\websocket.py", line 220, in __init__
    super().__init__(application, request, **kwargs)
  File "C:\Python\Python310\lib\site-packages\tornado\web.py", line 214, in __init__
    super().__init__()
  File "C:\Python\Python310\lib\typing.py", line 1422, in _no_init_or_replace_init
    cls.__init__(self, *args, **kwargs)
TypeError: WebSocketHandler.__init__() missing 2 required positional arguments: 'application' and 'request'

**Comment by VedankPurohit** [comment]
It doesn't look like an error in this projects execution. It's probably your python setup.

I am not an expert at this but it could be your network connection or you could just make a new environment and try

**Comment by guberm** [comment]
Updated the requirements.txt for it will work

numpy>=1.23.5
opencv_python==4.9.0.80
opencv_python_headless==4.9.0.80
Pillow==10.3.0
sentence_transformers==2.7.0
scikit-image
streamlit==1.32.2
torch
